import type { Position, Vault } from "./earnApi";
import { getBestApy } from "./earnApi";

/**
 * Calculates the total yearly USD savings/yield generated by the provided positions.
 */
export function calculateYearlyYield(positions: Position[]): number {
  return positions.reduce((sum, pos) => {
    const apy = getBestApy(pos.vault);
    const usdValue = pos.stakedTokenAmountUsd ?? 0;
    return sum + usdValue * apy;
  }, 0);
}

/**
 * Calculates how much yield has been earned overall (roughly)
 * since a position was created. 
 */
export function estimateTotalGrowth(positions: Position[]): number {
  // For a hackathon demo, let's assume an average of 7 days of growth 
  // if no other data is available, for visual impact.
  const days = 7; 
  return calculateYearlyYield(positions) * (days / 365);
}

function findVault(tx: any, vaultMap: Record<string, Vault>): Vault | undefined {
  const destToken = tx.receiving?.token?.address?.toLowerCase();
  const chainId = tx.receiving?.chainId;
  if (!destToken || !chainId) return undefined;
  
  const vaultKey = `${chainId}:${destToken}`;
  
  // 1. Direct match by receiving token (vault token)
  let vault: Vault | undefined = vaultMap[vaultKey];
  if (vault) return vault;

  // 2. Fallback: match by underlying asset if it's a known vault tool
  const tool = tx.tool?.toLowerCase();
  const vaultTools = ["yearn", "beefy", "stargate", "aave", "compound", "euler", "fluid", "morpho", "spark", "convex", "pendle", "lifi"];
  const isVaultTool = vaultTools.some(t => tool?.includes(t));
  
  if (isVaultTool) {
    vault = Object.values(vaultMap).find(v => 
      v.chainId === chainId && v.asset?.toLowerCase() === destToken
    );
    if (vault) return vault;
  }

  // 3. Last resort: Synthesize a vault object if the token name/symbol looks like a vault
  if (tx.receiving?.token) {
    const name = tx.receiving.token.name?.toLowerCase() || "";
    const symbol = tx.receiving.token.symbol?.toLowerCase() || "";
    
    const isAave = name.includes("aave") || 
                   symbol.startsWith("apusdc") || symbol.startsWith("amusdc") || 
                   symbol.startsWith("apol") || symbol.startsWith("aweth") || 
                   (symbol.startsWith("a") && symbol.length > 3);
    const isYearn = name.includes("yearn") || symbol.startsWith("yv");
    const isBeefy = name.includes("beefy") || symbol.startsWith("moo");
    const isStaked = name.includes("staked") || name.includes("yield") || symbol.startsWith("st") || symbol.startsWith("v");

    const isKnownVault = isAave || isYearn || isBeefy || isStaked;
    
    // Ignore common bridge/swap tools that aren't vaults
    const nonVaultTools = ["jupiter", "across", "hop", "gaszipbridge", "relaydepository", "mayan", "nordstern", "sushiswap", "symmetrie", "connext"];
    const isNonVaultTool = nonVaultTools.some(t => tool?.includes(t));
    if (isNonVaultTool && !isKnownVault) return undefined;
    
    if (isKnownVault) {
      console.log(`[findVault] Detected potential vault token: ${symbol} (${name}) on chain ${chainId}`);
      const toolName = tx.tool || (isAave ? "Aave" : isYearn ? "Yearn" : isBeefy ? "Beefy" : "DeFi");
      const protocolName = isAave ? "Aave" : isYearn ? "Yearn" : isBeefy ? "Beefy" : "DeFi";
      const tokenName = tx.receiving.token.symbol || tx.receiving.token.name || "Active Vault";
      
      // Deep link for Aave V3 Polygon if applicable
      const isAavePolygon = isAave && chainId === 137;
      const managementUrl = isAavePolygon 
        ? `https://app.aave.com/dashboard/?marketName=proto_polygon_v3`
        : protocolName === "Aave" ? "https://app.aave.com/" : "https://yearn.fi/vaults";

      return {
        id: `manual-${chainId}-${destToken}`,
        address: destToken,
        chainId: chainId,
        name: `${protocolName} ${tokenName}`,
        protocol: protocolName,
        asset: tx.sending?.token?.address || destToken,
        isTransactional: true,
        apy7d: 5.0,
        apy1d: 5.0,
        analytics: { apy: { base: 5, reward: 0, total: 5 }, tvl: { usd: "0" } },
        logoUrl: tx.receiving.token.logoURI || tx.receiving.token.logoUrl,
        decimals: tx.receiving.token.decimals,
        protocolLogoUrl: protocolName === "Aave" 
          ? "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9/logo.png" 
          : "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e/logo.png",
        url: managementUrl
      };
    }
  }

  return undefined;
}

/**
 * Synthesizes positions from transaction history for assets not yet in the Earn API.
 * This solves the indexing delay.
 */
export function synthesizePositionsFromHistory(
  history: any[],
  currentPositions: Position[],
  vaultMap: Record<string, Vault>
): Position[] {
  console.log(`[synthesize] Starting synthesis for ${history.length} txs`);
  const merged = [...currentPositions];
  const existingVaultIds = new Set(currentPositions.map(p => p.vault?.id).filter(Boolean));

  // Filter history for successful "DONE" transactions from the last 72h
  const now = Math.floor(Date.now() / 1000);
  const cutoff = now - (72 * 60 * 60);

  const recentSuccessfulTxs = history.filter(tx => {
    if (tx.status !== "DONE") return false;
    
    // Safety check for timestamp (LI.FI returns it in seconds)
    if (tx.timestamp && tx.timestamp < cutoff) return false;
    
    const vault = findVault(tx, vaultMap);
    if (!vault) return false;

    const isNew = !existingVaultIds.has(vault.id);
    if (!isNew) {
      return false;
    }

    console.log(`[synthesize] Found potential deposit: ${vault.name} (${tx.transactionId})`);
    existingVaultIds.add(vault.id);
    return true;
  });

  for (const tx of recentSuccessfulTxs) {
    const vault = findVault(tx, vaultMap);
    if (!vault) continue;

    try {
      const amountRaw = BigInt(tx.receiving.amount || "0");
      const decimals = tx.receiving.token.decimals ?? 18;
      const amountHuman = (Number(amountRaw) / 10 ** decimals).toString();

      const synthesized: Position = {
        id: `pending-${tx.transactionId}`,
        chainId: tx.receiving.chainId,
        vault: vault,
        userAddress: tx.fromAddress,
        stakedTokenAmount: amountHuman,
        stakedTokenAmountUsd: parseFloat(tx.receiving.amountUSD ?? "0"),
        txHash: tx.receiving?.txHash || tx.sending?.txHash,
        txLink: tx.lifiExplorerLink || tx.receiving?.txLink || tx.sending?.txLink,
      };

      merged.push(synthesized);
      existingVaultIds.add(vault.id);
      console.log(`[synthesize] Successfully synthesized position: ${vault.name} (${amountHuman} units)`);
    } catch (e) {
      console.error(`[synthesize] Failed to synthesize tx ${tx.transactionId}:`, e);
    }
  }

  return merged;
}
